
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
  
using System.Reflection;

[assembly: AssemblyVersion("0.46.0.0")]
[assembly: KSPAssembly("B9-PWings-Fork", 0, 46, 0)]
[assembly: KSPAssemblyDependency("ClickThroughBlocker", 1, 0)]
[assembly: KSPAssemblyDependency("ModuleManager", 1, 0)]